# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dfa4c15b-a755-4e92-8479-8ceff317eb4e";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };
  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/dfa4c15b-a755-4e92-8479-8ceff317eb4e";
      fsType = "btrfs";
      options = [ "subvol=nixos/var" ];
    };
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/dfa4c15b-a755-4e92-8479-8ceff317eb4e";
      fsType = "btrfs";
      options = [ "subvol=nixos/home" ];
    };
  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/dfa4c15b-a755-4e92-8479-8ceff317eb4e";
      fsType = "btrfs";
      options = [ "subvol=nixos/tmp" ];
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4501-257A";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c3a37ea8-82fb-4c7b-a33a-a283faf6f400"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  time.hardwareClockInLocalTime = true;
}
